development:
  clients:
    default:
      database: persoenlichkeitsDiagnostik_dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: persoenlichkeitsDiagnostik_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
