# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9023b9ed3b88937c845207ecdd8ef58b4bd523091434dadd68482ef0381a24c527801654a2ce47abce180c39032fc6ceab84cc136c717b9a05dbe377f562afd2

test:
  secret_key_base: e7207c9935a417d4a2c58b178c312a49ccacca161c9e4f56875d1ca69b7abb1f270dbf2ab90ecef825abf438d9cc11ed49e98f3725799bc25bcc6c5a88e8debd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
